name: terrbuy
main: org.gamegen.terrbuy
version: 0.0.0001
website: http://gamegen.org
author: stranger & Jegor
softdepend:
        - 'PermissionsEx'
        - 'WorldGuard'
        - 'WorldEdit'
description: >
                        Pay to be private.
commands:
  terrbuy:
        description: Buy a territory
        usage: /<command>
  terrclaim:
        description: Claim a territory
        usage: /<command> [region name] [price]